name: "Deploy Infrastructure"
description: "Deploy CALC infrastructure to specified environment"
inputs:
  environment:
    description: "Environment to deploy (staging or production)"
    required: true
  aws-account-id:
    description: "AWS Account ID"
    required: true
  oidc-role-name:
    description: "OIDC Role Name for AWS authentication"
    required: true
  mnemonic:
    description: "Mnemonic for worker secrets"
    required: true
  chain-id:
    description: "Chain ID for worker secrets"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.oidc-role-name }}
        role-session-name: GitHubActions-${{ inputs.environment }}
        aws-region: ap-southeast-1

    - name: Download image artifact
      uses: actions/download-artifact@v4
      with:
        name: worker-image

    - name: Load image
      shell: bash
      run: |
        gunzip -c worker.${{ github.sha }}.tar.gz | docker load
        docker image ls

    - name: Login ECR
      shell: bash
      run: |
        aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ inputs.aws-account-id }}.dkr.ecr.ap-southeast-1.amazonaws.com

    - name: Tag & Push
      shell: bash
      run: |
        SRC=calc-worker:${{ github.sha }}
        BASE=${{ inputs.aws-account-id }}.dkr.ecr.ap-southeast-1.amazonaws.com/calc-worker:${{ github.sha }}
        docker tag $SRC $BASE
        docker push $BASE

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.0

    - name: Terraform Init
      shell: bash
      run: |
        cd infrastructure
        terraform init -backend-config="bucket=calc-terraform-state-${{ inputs.environment }}"

    - name: Terraform Plan
      shell: bash
      run: |
        cd infrastructure
        terraform plan \
          -var="environment=${{ inputs.environment }}" \
          -var="container_image=${{ inputs.aws-account-id }}.dkr.ecr.ap-southeast-1.amazonaws.com/calc-worker:${{ github.sha }}" \
          -var="mnemonic=${{ inputs.mnemonic }}" \
          -var="chain_id=${{ inputs.chain-id }}" \
          -out=tfplan

    - name: Terraform Apply
      shell: bash
      run: |
        cd infrastructure
        terraform apply -auto-approve tfplan

    - name: Output Infrastructure Info
      shell: bash
      run: |
        echo "## 🚀 Deployment Complete - ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Container Image**: ${{ inputs.aws-account-id }}.dkr.ecr.ap-southeast-1.amazonaws.com/calc-worker:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Region**: ap-southeast-1" >> $GITHUB_STEP_SUMMARY
        echo "- **Terraform State**: calc-terraform-${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY

        # Get ECS cluster info
        cd infrastructure
        CLUSTER_NAME=$(terraform output -raw cluster_name 2>/dev/null || echo "calc-${{ inputs.environment }}-cluster")
        echo "- **ECS Cluster**: $CLUSTER_NAME" >> $GITHUB_STEP_SUMMARY

        # Get service status
        aws ecs describe-services \
          --cluster $CLUSTER_NAME \
          --services calc-${{ inputs.environment }}-execute-triggers calc-${{ inputs.environment }}-sync-transactions \
          --query 'services[].{Name:serviceName,Status:status,Running:runningCount,Desired:desiredCount}' \
          --output table >> $GITHUB_STEP_SUMMARY || echo "Services not yet available" >> $GITHUB_STEP_SUMMARY
