name: Deploy Infrastructure & Applications

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: calc-worker
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/worker/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Infrastructure
        uses: ./.github/actions/deploy-infrastructure
        with:
          environment: staging
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          oidc-role-name: ${{ secrets.OIDC_ROLE_NAME }}
          mnemonic: ${{ secrets.MNEMONIC }}
          chain-id: ${{ secrets.CHAIN_ID }}

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Infrastructure
        uses: ./.github/actions/deploy-infrastructure
        with:
          environment: production
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          oidc-role-name: ${{ secrets.OIDC_ROLE_NAME }}
          mnemonic: ${{ secrets.MNEMONIC }}
          chain-id: ${{ secrets.CHAIN_ID }}
